### ISSUE TITLE
How can I renew the menu? Or is pygame_menu static?

### ISSUE THREAD

**Issue by Jiang-yan-wei** [ppizarror/pygame-menu#208]
Hello! While using pygame_menu, I found a problem that, once the menu is created, it can not be renewed.
The detailed description:
I want to display my **character's information** on the button, but I found if the **character's information** is renewed, the string on button is still the old version. ( Maybe I failed to find the correct solution.....)
To show this problem, I did a small work on your example `game_selector.py`: 
line 209 and 210, I added a random number and `add_label` it and `print` it
But the number remains unchanged.....
The code is here:
```python
import sys

sys.path.insert(0, '../../')

import os
import pygame
import pygame_menu
import random

from random import randrange

# -----------------------------------------------------------------------------
# Constants and global variables
# -----------------------------------------------------------------------------
ABOUT = ['pygame-menu {0}'.format(pygame_menu.__version__),
         'Author: @{0}'.format(pygame_menu.__author__),
         ' ',  # new line
         'Email: {0}'.format(pygame_menu.__email__)]
DIFFICULTY = ['EASY']
FPS = 60.0
WINDOW_SIZE = (640, 480)

clock = None  # type: pygame.time.Clock
main_menu = None  # type: pygame_menu.Menu
surface = None  # type: pygame.Surface


# -----------------------------------------------------------------------------
# Methods
# -----------------------------------------------------------------------------
def change_difficulty(value, difficulty):
    """
    Change difficulty of the game.
    :param value: Tuple containing the data of the selected object
    :type value: tuple
    :param difficulty: Optional parameter passed as argument to add_selector
    :type difficulty: str
    :return: None
    """
    selected, index = value
    print('Selected difficulty: "{0}" ({1}) at index {2}'.format(selected, difficulty, index))
    DIFFICULTY[0] = difficulty


def random_color():
    """
    Return random color.
    :return: Color tuple
    :rtype: tuple
    """
    return randrange(0, 255), randrange(0, 255), randrange(0, 255)


def play_function(difficulty, font, test=False):
    """
    Main game function.
    :param difficulty: Difficulty of the game
    :type difficulty: tuple, list
    :param font: Pygame font
    :type font: :py:class:`pygame.font.Font`
    :param test: Test method, if true only one loop is allowed
    :type test: bool
    :return: None
    """
    assert isinstance(difficulty, (tuple, list))
    difficulty = difficulty[0]
    assert isinstance(difficulty, str)

    # Define globals
    global main_menu
    global clock

    if difficulty == 'EASY':
        f = font.render('Playing as a baby (easy)', 1, (255, 255, 255))
    elif difficulty == 'MEDIUM':
        f = font.render('Playing as a kid (medium)', 1, (255, 255, 255))
    elif difficulty == 'HARD':
        f = font.render('Playing as a champion (hard)', 1, (255, 255, 255))
    else:
        raise Exception('Unknown difficulty {0}'.format(difficulty))

    # Draw random color and text
    bg_color = random_color()
    f_width = f.get_size()[0]

    # Reset main menu and disable
    # You also can set another menu, like a 'pause menu', or just use the same
    # main_menu as the menu that will check all your input.
    main_menu.disable()
    main_menu.reset(1)

    while True:

        # noinspection PyUnresolvedReferences
        clock.tick(60)

        # Application events
        events = pygame.event.get()
        for e in events:
            if e.type == pygame.QUIT:
                exit()
            elif e.type == pygame.KEYDOWN:
                if e.key == pygame.K_ESCAPE:
                    main_menu.enable()

                    # Quit this function, then skip to loop of main-menu on line 317
                    return

        # Pass events to main_menu
        main_menu.update(events)

        # Continue playing
        surface.fill(bg_color)
        surface.blit(f, ((WINDOW_SIZE[0] - f_width) / 2, WINDOW_SIZE[1] / 2))
        pygame.display.flip()

        # If test returns
        if test:
            break


def main_background():
    """
    Function used by menus, draw on background while menu is active.
    :return: None
    """
    global surface
    surface.fill((128, 0, 128))


def main(test=False):
    """
    Main program.
    :param test: Indicate function is being tested
    :type test: bool
    :return: None
    """

    # -------------------------------------------------------------------------
    # Globals
    # -------------------------------------------------------------------------
    global clock
    global main_menu
    global surface

    # -------------------------------------------------------------------------
    # Init pygame
    # -------------------------------------------------------------------------
    pygame.init()
    os.environ['SDL_VIDEO_CENTERED'] = '1'

    # Create pygame screen and objects
    surface = pygame.display.set_mode(WINDOW_SIZE)
    pygame.display.set_caption('Example - Game Selector')
    clock = pygame.time.Clock()

    # -------------------------------------------------------------------------
    # Create menus: Play Menu
    # -------------------------------------------------------------------------
    play_menu = pygame_menu.Menu(
        height=WINDOW_SIZE[1] * 0.7,
        onclose=pygame_menu.events.DISABLE_CLOSE,
        title='Play Menu',
        width=WINDOW_SIZE[0] * 0.7,
    )

    submenu_theme = pygame_menu.themes.THEME_DEFAULT.copy()
    submenu_theme.widget_font_size = 15
    play_submenu = pygame_menu.Menu(
        height=WINDOW_SIZE[1] * 0.5,
        theme=submenu_theme,
        title='Submenu',
        width=WINDOW_SIZE[0] * 0.7,
    )
    for i in range(30):
        play_submenu.add_button('Back {0}'.format(i), pygame_menu.events.BACK)
    play_submenu.add_button('Return to main menu', pygame_menu.events.RESET)

    play_menu.add_button('Start',  # When pressing return -> play(DIFFICULTY[0], font)
                         play_function,
                         DIFFICULTY,
                         pygame.font.Font(pygame_menu.font.FONT_FRANCHISE, 30))
    play_menu.add_selector('Select difficulty ',
                           [('1 - Easy', 'EASY'),
                            ('2 - Medium', 'MEDIUM'),
                            ('3 - Hard', 'HARD')],
                           onchange=change_difficulty,
                           selector_id='select_difficulty')
    play_menu.add_button('Another menu', play_submenu)
    play_menu.add_button('Return to main menu', pygame_menu.events.BACK)

    # -------------------------------------------------------------------------
    # Create menus:About
    # -------------------------------------------------------------------------
    about_theme = pygame_menu.themes.THEME_DEFAULT.copy()
    about_theme.widget_margin = (0, 0)
    about_theme.widget_offset = (0, 0.05)

    about_menu = pygame_menu.Menu(
        height=WINDOW_SIZE[1] * 0.6,
        onclose=pygame_menu.events.DISABLE_CLOSE,
        theme=about_theme,
        title='About',
        width=WINDOW_SIZE[0] * 0.6,
    )
    for m in ABOUT:
        about_menu.add_label(m, align=pygame_menu.locals.ALIGN_LEFT, font_size=20)
    number = random.randint(0,10)
    about_menu.add_label('{0}'.format(number))
    print(number)
    about_menu.add_label(' ')
    about_menu.add_button('Return to menu', pygame_menu.events.BACK)

    # -------------------------------------------------------------------------
    # Create menus: Main
    # -------------------------------------------------------------------------
    main_menu = pygame_menu.Menu(
        back_box=False,
        height=WINDOW_SIZE[1] * 0.6,
        onclose=pygame_menu.events.DISABLE_CLOSE,
        title='Main Menu',
        width=WINDOW_SIZE[0] * 0.6,
    )

    main_menu.add_button('Play', play_menu)
    main_menu.add_button('About', about_menu)
    main_menu.add_button('Quit', pygame_menu.events.EXIT)

    # -------------------------------------------------------------------------
    # Main loop
    # -------------------------------------------------------------------------
    while True:

        # Tick
        clock.tick(FPS)

        # Paint background
        main_background()

        # Application events
        events = pygame.event.get()
        for event in events:
            if event.type == pygame.QUIT:
                exit()

        # Main menu
        main_menu.mainloop(surface, main_background, disable_loop=test, fps_limit=FPS)

        # Flip surface
        pygame.display.flip()

        # At first loop returns
        if test:
            break


if __name__ == '__main__':
    main()
```
Thank you for considering my problem!

**Comment by ppizarror** [comment]
Hi! In your example, I couldn't find the issue, It worked as expected

As you added a label to about_menu, It worked as intended
![image](https://user-images.githubusercontent.com/12925256/84446951-be490000-ac14-11ea-91fc-946465e4a37f.png)

**Comment by ppizarror** [comment]
Also created the following example (development) and widget update on runtime is working as expected.

```python
import sys
sys.path.insert(0, '../../')
import pygame_menu
from random import randrange
import pygame
import os

pygame.init()
os.environ['SDL_VIDEO_CENTERED'] = '1'
surface = pygame.display.set_mode((600, 400))

menu = pygame_menu.Menu(height=300,
                        width=400,
                        theme=pygame_menu.themes.THEME_BLUE,
                        title='Welcome')


def add_dynamic_button():
    print('Adding a button dynamically')
    btn = menu.add_button(randrange(0, 10), pygame_menu.events.NONE)

    def _update_button():
        count = btn.get_attribute('count', int(btn.get_title())) + 1
        btn.set_title(count)
        btn.set_attribute('count', count)

    btn.update_callback(_update_button)


menu.add_text_input('Name: ', default='John Doe')
menu.add_button('Play', add_dynamic_button)
menu.add_button('Quit', pygame_menu.events.EXIT)

if __name__ == '__main__':
    menu.mainloop(surface)

```

**Comment by Jiang-yan-wei** [comment]
> Hi! In your example, I couldn't find the issue, It worked as expected
> 
> As you added a label to about_menu, It worked as intended. Tested in both py2.7 and py3.7
> ![image](https://user-images.githubusercontent.com/12925256/84446951-be490000-ac14-11ea-91fc-946465e4a37f.png)

## reply to your first comment
Sorry, I did not make myself clear......
I mean that, if you return to `mainmenu` from `aboutmenu`, and click `aboutmenu` again, the random number will always be one certain number('0' in your example), actually the random function only runs once. But I want it to be a new random number every time I open the `aboutmenu`. 
Like this:


![demo](https://user-images.githubusercontent.com/50770474/84456035-8f24a400-ac91-11ea-9e33-44815c7a6dde.gif)


## reply to your second comment
Thank you for your example of dynamic button in your second commet, but, I came across some errors.
The first error is that the title of a button must be a string, so I changed the line 20 to convert int to string:
`btn = menu.add_button('{0}'.format(randrange(0, 10)), pygame_menu.events.NONE)`
But there is another error: 
` AttributeError: 'Button' object has no attribute 'update_callback' `
I checked `button.py` but no `update_callback` function...
My pygame version: `2.0.0.dev8` (my friend's is 1.9.6 but we have the same error.)
My pygamemenu version: `3.0.3` (my friends is 3.0.1 but the same error)
My python version: `3.7.2`

Like this:
![demo2](https://user-images.githubusercontent.com/50770474/84456052-9d72c000-ac91-11ea-8041-76d7cd5f416b.gif)



The full error message:
```
C:\Users\1>python -u "c:\Users\1\Desktop\menutest.py"
pygame 2.0.0.dev8 (SDL 2.0.12, python 3.7.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Adding a button dynamically
Traceback (most recent call last):
  File "c:\Users\1\Desktop\menutest.py", line 35, in <module>
    menu.mainloop(surface)
  File "C:\Users\1\AppData\Local\Programs\Python\Python37\lib\site-packages\pygame_menu\menu.py", line 1667, in mainloop
    self.update(pygame.event.get())
  File "C:\Users\1\AppData\Local\Programs\Python\Python37\lib\site-packages\pygame_menu\menu.py", line 1602, in update
    selected_widget.update((new_event,))  # This widget can change the current Menu to a submenu
  File "C:\Users\1\AppData\Local\Programs\Python\Python37\lib\site-packages\pygame_menu\widgets\widget\button.py", line 106, in update
    self.apply()
  File "C:\Users\1\AppData\Local\Programs\Python\Python37\lib\site-packages\pygame_menu\widgets\core\widget.py", line 278, in apply
    return self._on_return(*args, **self._kwargs)
  File "c:\Users\1\Desktop\menutest.py", line 27, in add_dynamic_button
    btn.update_callback(_update_button)
AttributeError: 'Button' object has no attribute 'update_callback'
```

**Comment by ppizarror** [comment]
> > Hi! In your example, I couldn't find the issue, It worked as expected
> > As you added a label to about_menu, It worked as intended. Tested in both py2.7 and py3.7
> > ![image](https://user-images.githubusercontent.com/12925256/84446951-be490000-ac14-11ea-91fc-946465e4a37f.png)
> 
> ## reply to your first comment
> Sorry, I did not make myself clear......
> I mean that, if you return to `mainmenu` from `aboutmenu`, and click `aboutmenu` again, the random number will always be one certain number('0' in your example), actually the random function only runs once. But I want it to be a new random number every time I open the `aboutmenu`.
> Like this:
> 
> ![demo](https://user-images.githubusercontent.com/50770474/84456035-8f24a400-ac91-11ea-9e33-44815c7a6dde.gif)
> 
> ## reply to your second comment
> Thank you for your example of dynamic button in your second commet, but, I came across some errors.
> The first error is that the title of a button must be a string, so I changed the line 20 to convert int to string:
> `btn = menu.add_button('{0}'.format(randrange(0, 10)), pygame_menu.events.NONE)`
> But there is another error:
> `AttributeError: 'Button' object has no attribute 'update_callback'`
> I checked `button.py` but no `update_callback` function...
> My pygame version: `2.0.0.dev8` (my friend's is 1.9.6 but we have the same error.)
> My pygamemenu version: `3.0.3` (my friends is 3.0.1 but the same error)
> My python version: `3.7.2`
> 
> Like this:
> ![demo2](https://user-images.githubusercontent.com/50770474/84456052-9d72c000-ac91-11ea-8041-76d7cd5f416b.gif)
> 
> The full error message:
> 
> ```
> C:\Users\1>python -u "c:\Users\1\Desktop\menutest.py"
> pygame 2.0.0.dev8 (SDL 2.0.12, python 3.7.2)
> Hello from the pygame community. https://www.pygame.org/contribute.html
> Adding a button dynamically
> Traceback (most recent call last):
>   File "c:\Users\1\Desktop\menutest.py", line 35, in <module>
>     menu.mainloop(surface)
>   File "C:\Users\1\AppData\Local\Programs\Python\Python37\lib\site-packages\pygame_menu\menu.py", line 1667, in mainloop
>     self.update(pygame.event.get())
>   File "C:\Users\1\AppData\Local\Programs\Python\Python37\lib\site-packages\pygame_menu\menu.py", line 1602, in update
>     selected_widget.update((new_event,))  # This widget can change the current Menu to a submenu
>   File "C:\Users\1\AppData\Local\Programs\Python\Python37\lib\site-packages\pygame_menu\widgets\widget\button.py", line 106, in update
>     self.apply()
>   File "C:\Users\1\AppData\Local\Programs\Python\Python37\lib\site-packages\pygame_menu\widgets\core\widget.py", line 278, in apply
>     return self._on_return(*args, **self._kwargs)
>   File "c:\Users\1\Desktop\menutest.py", line 27, in add_dynamic_button
>     btn.update_callback(_update_button)
> AttributeError: 'Button' object has no attribute 'update_callback'
> ```

I know, that methods are available in version 3.1.0. I'll push the new changes asap

**Comment by Jiang-yan-wei** [comment]
Many thanks for your kind help！I 'll wait for this!

**Comment by ppizarror** [comment]
New version uploaded, check pip!

**Comment by Jiang-yan-wei** [comment]
I got that! Many many many many thanks! I will report my feeling to you after finishing my project!
