### ISSUE TITLE
Cannot import pygame-menu v3.3.0 with pygame v2.0.0 on raspberry pi

### ISSUE THREAD

**Issue by werdeil** [ppizarror/pygame-menu#221]
Hi @ppizarror and @anxuae 

Since the release of pygame 2.2.0 we have an issue on pygame-menu at the import:

```
 File "/usr/local/lib/python3.7/dist-packages/pygame_menu/__init__.py", line 51, in <module>
    import pygame_menu.font
  File "/usr/local/lib/python3.7/dist-packages/pygame_menu/font.py", line 34, in <module>
    import pygame.font as _font
ImportError: libSDL2_ttf-2.0.so.0: cannot open shared object file: No such file or directory
```

Any idea?

**Comment by werdeil** [comment]
Seems to be on pygame side: `import pygame.font` causes this issue.

**Comment by ppizarror** [comment]
As for now the tests passes. Can you provide a complete example to figure
out how to solve this? (Maybe you are using a custom font....)

**Comment by werdeil** [comment]
As I said I'm on a raspberry pi with python 3.7.3, and it happens directly when importing pygame-menu (when it imports pygame.fonts) but from what I see it is an issue with the rapsberry pi version of the pygame package as I have the issue when doing directly the import.

```
pi@raspberrypi:~ $ python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygame_menu
pygame 2.0.0 (SDL 2.0.9, python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/pygame_menu/__init__.py", line 51, in <module>
    import pygame_menu.font
  File "/usr/local/lib/python3.7/dist-packages/pygame_menu/font.py", line 34, in <module>
    import pygame.font as _font
ImportError: libSDL2_ttf-2.0.so.0: cannot open shared object file: No such file or directory
>>> import pygame.font
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libSDL2_ttf-2.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by werdeil** [comment]
I found the issue, seems to be linked to new apt packages necessary to install before pygame. Closing this thread, as it is not pygame-menu related.

Sorry for the disturbance.
