### ISSUE TITLE
RangeSlider assertion error when modifying minimum range value

### ISSUE THREAD

**Issue by JKornberg** [ppizarror/pygame-menu#356]
**Environment information**
Describe your environment information, such as:
- SO: Windows
- python version: v3.8.5
- pygame version: v2.0.1
- pygame-menu version: v4.1.0

**Describe the bug**
    `options.add.range_slider("Infection Rate", default = 2,increment=0.5, range_values=(2,10))`

This line throws an assertion error shown below. If the minimum value is set to 0, this works fine. It appears almost any minimum range value other than 0 throws an error. Commenting out the assertion in source seemed to work fine.

`Traceback (most recent call last):
  File "main.py", line 120, in <module>
    g = Game()
  File "main.py", line 25, in __init__
    self.options = optionsMenu(lambda : self._update_from_selection(3))
  File "D:\School\Python\Sickulator\src\sickulator\menus.py", line 29, in optionsMenu
    options.add.range_slider("Infection Rate", default = 2,increment=0.5, range_values=(2,10))
  File "C:\Users\JBKec\anaconda3\envs\game\lib\site-packages\pygame_menu\_widgetmanager.py", line 2816, in range_slider
    self._configure_widget(widget=widget, **attributes)
  File "C:\Users\JBKec\anaconda3\envs\game\lib\site-packages\pygame_menu\_widgetmanager.py", line 305, in _configure_widget
    widget.set_font(
  File "C:\Users\JBKec\anaconda3\envs\game\lib\site-packages\pygame_menu\widgets\core\widget.py", line 1711, in set_font
    self._force_render()
  File "C:\Users\JBKec\anaconda3\envs\game\lib\site-packages\pygame_menu\widgets\core\widget.py", line 802, in _force_render
    return self._render()
  File "C:\Users\JBKec\anaconda3\envs\game\lib\site-packages\pygame_menu\widgets\widget\rangeslider.py", line 795, in _render
    st_x = self._range_pos[0] + self._get_pos_range(v, st)
  File "C:\Users\JBKec\anaconda3\envs\game\lib\site-packages\pygame_menu\widgets\widget\rangeslider.py", line 819, in _get_pos_range
    assert 0 <= d <= 1
AssertionError`

**To Reproduce**
Create a menu, add a range_slider with range_values of 2 to 10 (or any number other than 0 to any value).

**Expected behavior**
It should successfully produce the range slider

**Comment by ppizarror** [comment]
Hi, I'll look at it and fix asap

**Comment by ppizarror** [comment]
I've patched it in #357, let me know if this solves your issue to pull the new version.

**Comment by JKornberg** [comment]
> I've patched it in #357, let me know if this solves your issue to create the new version.

This works great! Thank you so much, I am closing the issue.

**Comment by ppizarror** [comment]
Excellent. The new version has already been uploaded to PyPI.

If you've any other issue or suggestion just create a new issue 😄
