### ISSUE TITLE
Valor por defecto de de textinput y maxwidth

### ISSUE THREAD

**Issue by BautistaCRP** [ppizarror/pygame-menu#92]
Hola tengo un error cuando a un text_input trato de asigarle un valor por defecto y al mismo tiempo intento limitar el ancho maximo del mismo usando maxwidth=10

`test_menu.add_text_input('Holis ',textinput_id='id1', maxwidth=10, maxchar=20, default="ABCDEFG")`

El error es el siguiente:

`Traceback (most recent call last):
  File "/home/bautista/PycharmProjects/pacman/pacman/dqn/__init__.py", line 185, in <module>
    test_menu.add_text_input('Holis ',textinput_id='id1', maxwidth=10, maxchar=20, default="ABCDEFG")
  File "/home/bautista/.local/lib/python3.6/site-packages/pygameMenu/menu.py", line 586, in add_text_input
    **kwargs)
  File "/home/bautista/.local/lib/python3.6/site-packages/pygameMenu/widgets/textinput.py", line 262, in __init__
    self.set_value(default)
  File "/home/bautista/.local/lib/python3.6/site-packages/pygameMenu/widgets/textinput.py", line 889, in set_value
    self._move_cursor_right()
  File "/home/bautista/.local/lib/python3.6/site-packages/pygameMenu/widgets/textinput.py", line 956, in _move_cursor_right
    self._update_renderbox(right=1)
  File "/home/bautista/.local/lib/python3.6/site-packages/pygameMenu/widgets/textinput.py", line 740, in _update_renderbox
    self._update_maxlimit_renderbox()
  File "/home/bautista/.local/lib/python3.6/site-packages/pygameMenu/widgets/textinput.py", line 762, in _update_maxlimit_renderbox
    accum_size += self._keychar_size[char]
KeyError: 'A'`

**Comment by ppizarror** [comment]
cierto. Revisaré que está pasando y daré algunas novedades

**Comment by ppizarror** [comment]
Arreglado #93 aunque

**Comment by ppizarror** [comment]
Corregido, en la próxima versión de estos días (v2.2

**Comment by BautistaCRP** [comment]
Genial!! Ya lo pude probar y funciona genial, muchas gracias!
